### PR TITLE
Enhancement: TextView Drawable Matcher 

### PR DESCRIPTION
**Pull request by RobertKeazor**
@heitorcolangelo I'll create a sample app and write test, if your ok with the logic

### CODE REVIEW

**Comment by heitorcolangelo** [comment]
@RobertKeazor I'm ok with the logic. But can you write a sample test using this logic in the sample app?

**Comment by RobertKeazor** [comment]
@heitorcolangelo  Sure, do you want me to create another Sample Activity  or just add tests to  one existing ones that are already there?

**Comment by heitorcolangelo** [comment]
Feel free to choose wich one you prefer. I had to organize the sample app in the future, so for now there's no pattern to follow

**Comment by RobertKeazor** [comment]
@heitorcolangelo Tests added

**Pull request merged**
